version: 2.1
orbs:
  compare-url: iynere/compare-url@0.4.10
jobs:
  build:
    working_directory: /go/src/github.com/cvcio/elections-api
    docker:
    - image: golang:1.12.5
    steps:
    - checkout
    - compare-url/reconstruct
    - setup_remote_docker:
        version: 17.11.0-ce
    - run:
        name: build
        shell: /bin/bash
        command: |
          # save value stored in file to a local env var
          CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)
          git config --global url."https://$GITHUB_TOKEN:@github.com/".insteadOf "https://github.com/"
          chmod +x ./build.sh
          ./build.sh
  build_brach:
    working_directory: /go/src/github.com/cvcio/elections-api
    docker:
    - image: golang:1.12.5
    steps:
    - checkout
    # - compare-url/reconstruct
    - setup_remote_docker:
        version: 17.11.0-ce
    - run:
        name: build
        shell: /bin/bash
        command: |
          # save value stored in file to a local env var
          # CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)
          git config --global url."https://$GITHUB_TOKEN:@github.com/".insteadOf "https://github.com/"
          chmod +x ./build.sh
          ./build.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
         filters:
            branches: { only: 'master' }
      - build_branch:
         filters:
            branches: { ignore: 'master' }
